import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

import Layout from "../components/Layout";
import InnerPageHeader from "../components/InnerPageHeader";
import LargeCircleSection from "../components/LargeCircleSection";
import SmallCircleSection from "../components/SmallCircleSection";
import FAQSection from "../components/FAQSection";

import { largeCircleDataAbout } from "../data/largeCircleData";
import { smallCircleData } from "../data/smallCircleData";
import { FAQData } from "../data/FAQData";

const inter = Inter({ subsets: ["latin"] });

export default function About() {
  // const FAQSectionData = [
  //   {
  //     question: "How do I download the app?",
  //     answer: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum.",
  //   },
  //   {
  //     question: "How do I download the app?",
  //     answer: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum.",
  //   },
  //   {
  //     question: "How do I download the app?",
  //     answer: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum.",
  //   },
  // ];

  return (
    <>
      <Head>
        <title>Scoot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <InnerPageHeader
          title="About"
          imgSrc="/assets/images/about-hero-desktop.jpg"
          alt="placeholder"
        />
        <LargeCircleSection largeCircleDataHome={largeCircleDataAbout} />
        <SmallCircleSection
          header={"Our values"}
          smallCircleData={smallCircleData}
        />
        <FAQSection FAQSectionData={FAQData} />
      </Layout>
    </>
  );
}
