import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

import Layout from "../components/Layout";
import InnerPageHeader from "../components/InnerPageHeader";
import LargeCircleSection from "../components/LargeCircleSection";
import SmallCircleSection from "../components/SmallCircleSection";

import { largeCircleDataCareers } from "../data/largeCircleData";
import { smallCircleData } from "../data/smallCircleData";

const inter = Inter({ subsets: ["latin"] });

export default function About() {
  return (
    <>
      <Head>
        <title>Scoot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <InnerPageHeader
          title="Careers "
          imgSrc="/assets/images/careers-locations-hero-desktop.jpg"
          alt="placeholder"
        />
        <LargeCircleSection largeCircleDataHome={largeCircleDataCareers} />
        <SmallCircleSection
          header={"Why join us?"}
          smallCircleData={smallCircleData}
        />
      </Layout>
    </>
  );
}
