import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Layout from "../components/Layout";
import InnerPageHeader from "../components/InnerPageHeader";

const inter = Inter({ subsets: ["latin"] });

export default function Locations() {
  return (
    <>
      <Head>
        <title>Scoot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <InnerPageHeader
          title="Locations"
          imgSrc="/assets/images/careers-locations-hero-desktop.jpg"
          alt="placeholder"
        />
      </Layout>
    </>
  );
}
